#!/usr/bin/env python3
"""sessionStart: install the CLI shims, and warn about a missing key before it matters.

Two jobs.

**1. Make the tools reachable from the agent's shell.**

Verified 2026-08-08: `CURSOR_PLUGIN_ROOT` is set for *hooks* but is NOT visible to the
agent's shell tool, and env returned by this hook reaches later hooks but also not the
shell. So a skill cannot say `python3 "$CURSOR_PLUGIN_ROOT/scripts/damira.py"` — the
variable is empty there and the command fails.

What the shell *does* inherit is the user's environment and the filesystem. So this hook
writes tiny exec shims at a stable absolute path:

    ~/.damira/bin/damira
    ~/.damira/bin/damira-audit-config

Skills invoke those. The shims are rewritten on every session start, so a plugin update,
a version bump, or a move to a different install location is picked up automatically —
there is nothing for the user to reinstall and nothing to go stale.

The plugin root is resolved from __file__ rather than the env var, so this works
identically under `--plugin-dir`, a marketplace install, or a symlink into
~/.cursor/plugins/local.

**2. Surface a missing key now rather than mid-incident.**

Never blocks — the shared demo key still answers 50 queries/day.
"""

import json
import os
import stat
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
BIN_DIR = Path.home() / ".damira" / "bin"
CONFIG_PATH = Path.home() / ".damira" / "config"

SHIMS = {
    "damira": PLUGIN_ROOT / "scripts" / "damira.py",
    "damira-audit-config": PLUGIN_ROOT / "scripts" / "audit_config.py",
}

# The plugin's own mcp.json points at a stable path under ~/.damira/bin so it does not
# have to hardcode an install location. Cursor's CLI does not load plugin-bundled MCP at
# all (verified 2026-08-08), so this only matters for the IDE, where plugin mcp.json is
# documented to work. Costs nothing to keep current either way.
MCP_LINK_NAME = "damira-mcp-server.py"
MCP_SERVER = PLUGIN_ROOT / "mcp" / "server.py"


def install_shims() -> "list[str]":
    """Write exec shims; return the names installed. Best-effort by design."""
    installed = []
    try:
        BIN_DIR.mkdir(parents=True, exist_ok=True)
    except OSError:
        return installed

    for name, target in SHIMS.items():
        if not target.is_file():
            continue
        shim = BIN_DIR / name
        body = (
            "#!/bin/sh\n"
            "# Generated by the Damira Cursor plugin on session start. Do not edit —\n"
            "# it is rewritten every session to track the current plugin install.\n"
            f'exec python3 "{target}" "$@"\n'
        )
        try:
            if shim.is_file() and shim.read_text(encoding="utf-8") == body:
                installed.append(name)
                continue
            shim.write_text(body, encoding="utf-8")
            shim.chmod(shim.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            installed.append(name)
        except OSError:
            continue

    # Keep the MCP server reachable at a stable path for the plugin's mcp.json.
    if MCP_SERVER.is_file():
        link = BIN_DIR / MCP_LINK_NAME
        try:
            if link.is_symlink() or link.exists():
                if link.resolve() != MCP_SERVER.resolve():
                    link.unlink()
                    link.symlink_to(MCP_SERVER)
            else:
                link.symlink_to(MCP_SERVER)
        except OSError:
            pass  # non-fatal: install-mcp writes an absolute path and does not need this

    return installed


def has_key() -> bool:
    if os.environ.get("DAMIRA_API_KEY", "").strip():
        return True
    if CONFIG_PATH.is_file():
        try:
            return bool(CONFIG_PATH.read_text(encoding="utf-8").strip())
        except OSError:
            return False
    return False


def main() -> None:
    try:
        sys.stdin.read()
    except Exception:  # noqa: BLE001 — a stdin hiccup must not break session start
        pass

    installed = install_shims()
    mode = os.environ.get("DAMIRA_EXECUTION_MODE", "advisor").strip().lower()

    notes = []

    if installed:
        notes.append(
            "Damira CLI is available at ~/.damira/bin/damira (and "
            "~/.damira/bin/damira-audit-config for local config audits). Invoke those "
            "paths directly — do not look for an MCP server or a damira.py in the "
            "workspace."
        )
    else:
        notes.append(
            "WARNING: the Damira CLI shims could not be installed under ~/.damira/bin. "
            f"Invoke the scripts by absolute path instead: {PLUGIN_ROOT}/scripts/damira.py"
        )

    if not has_key():
        notes.append(
            "Damira is running on the shared demo key (50 queries/day) — no personal key "
            "is set. If a command fails with a plan or rate-limit error, tell the engineer "
            "to get a key at https://damiraai.com/dashboard/api-keys and add "
            "`export DAMIRA_API_KEY=...` to their shell profile (or write it to "
            "~/.damira/config). Do not retry in a loop."
        )

    if mode != "advisor":
        notes.append(
            f"Damira execution mode is '{mode}', not advisor. Read-only show commands on "
            "lab devices are permitted. Configuration changes, clear commands, and reloads "
            "are never permitted regardless of mode."
        )

    print(json.dumps({
        "env": {"DAMIRA_EXECUTION_MODE": mode},
        "additional_context": " ".join(notes),
    }))


if __name__ == "__main__":
    try:
        main()
    except Exception:  # noqa: BLE001 — informational hook, must never block a session
        print(json.dumps({}))
    sys.exit(0)
